Vagrant.configure("2") do |config|

  # Set the base box
  config.vm.box = "ubuntu/jammy64"

  # Network configuration
  config.vm.network "public_network", bridge: "eno1.100"
  
  # Provider-specific configuration for VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant-with-Ansible-VM"
    vb.memory = "2024"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Ansible provisioner to run a playbook
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end

  # Additional configurations
  config.vm.hostname = "Vagrant-with-Ansible-VM"

end
