export let kanbanData: Object[] = [
  {
    Id: 'Task 1',
    Project: 'Project 1',
    Title: 'Task - 29001',
    Status: ' ',
    Summary: 'Analyze the new requirements gathered from the customer.',
    Type: 'Story',
    Priority: 'Low',
    Tags: 'Analyze,Customer',
    StoryPoints: 3.5,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 1, */
    // Color: '#008000',
    // ClassName: 'e-story, e-low, e-nancy-davloio',
  },
  {
    Id: 'Task 2',
    Project: 'Project 2',
    Title: 'Task - 29002',
    Status: 'InProgress',
    Summary: 'Improve application performance',
    Type: 'Improvement',
    Priority: 'Normal',
    Tags: 'Improvement',
    StoryPoints: 6,
    Assignee: 'Andrew Fuller',
    /* 'RankId': 1, */
    // Color: '#5187c6',
    // ClassName: 'e-improvement, e-normal, e-andrew-fuller',
  },
  {
    Id: 'Task 3',
    Project: 'Project 3',
    Title: 'Task - 29003',
    Status: 'InProgress',
    Summary: 'Arrange a web meeting with the customer to get new requirements.',
    Type: 'Others',
    Priority: 'Critical',
    Tags: 'Meeting',
    StoryPoints: 5.5,
    Assignee: 'Janet Leverling',
    /* 'RankId': 2, */
    // Color: '#5187c6',
    // ClassName: 'e-others, e-critical, e-janet-leverling',
  },
  {
    Id: 'Task 4',
    Project: 'Project 4',
    Title: 'Task - 29004',
    Status: 'InProgress',
    Summary: 'Fix the issues reported in the IE browser.',
    Type: 'Bug',
    Priority: 'Release Breaker',
    Tags: 'IE',
    StoryPoints: 2.5,
    Assignee: 'Janet Leverling',
    /* 'RankId': 2, */
    // Color: '#ff0000',
    // ClassName: 'e-bug, e-release, e-janet-leverling',
  },
  {
    Id: 'Task 5',
    Project: 'Project 5',
    Title: 'Task - 29005',
    Status: 'Review',
    Summary: 'Fix the issues reported by the customer.',
    Type: 'Bug',
    Priority: 'Low',
    Tags: 'Customer',
    StoryPoints: '3.5',
    Assignee: 'Steven walker',
    /* 'RankId': 1, */
    // Color: '#ff0000',
    // ClassName: 'e-bug, e-low, e-steven-walker',
  },
  {
    Id: 'Task 6',
    Project: 'Project 6',
    Title: 'Task - 29007',
    Status: 'Review',
    Summary: 'Validate new requirements',
    Type: 'Improvement',
    Priority: 'Low',
    Tags: 'Validation',
    StoryPoints: 1.5,
    Assignee: 'Robert King',
    /* 'RankId': 1, */
    // Color: '#57b94c',
    // ClassName: 'e-improvement, e-low, e-robert-king',
  },
  {
    Id: 'Task 7',
    Project: 'Project 6',
    Title: 'Task - 29009',
    Status: 'Review',
    Summary: 'Fix the issues reported in Safari browser.',
    Type: 'Epic',
    Priority: 'Release Breaker',
    Tags: 'Fix,Safari',
    StoryPoints: 1.5,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 2, */
    // Color: '#ff0000',
    // ClassName: 'e-epic, e-release, e-nancy-davloio',
  },
  {
    Id: 'Task 8',
    Project: 'Project 5',
    Title: 'Task - 29010',
    Status: 'Close',
    Summary: 'Test the application in the IE browser.',
    Type: 'Story',
    Priority: 'Low',
    Tags: 'Review,IE',
    StoryPoints: 5.5,
    Assignee: 'Margaret hamilt',
    /* 'RankId': 3, */
    // Color: '#008000',
    // ClassName: 'e-story, e-low, e-margaret-hamilt',
  },
  {
    Id: 'Task 9',
    Project: 'Project 4',
    Title: 'Task - 29011',
    Status: 'InProgress',
    Summary: 'Validate the issues reported by the customer.',
    Type: 'Story',
    Priority: 'High',
    Tags: 'Validation,Fix',
    StoryPoints: 1,
    Assignee: 'Steven walker',
    /* 'RankId': 1, */
    // Color: '#008000',
    // ClassName: 'e-story, e-high, e-steven-walker',
  },
  {
    Id: 'Task 10',
    Project: 'Project 3',
    Title: 'Task - 29015',
    Status: 'Open',
    Summary: 'Show the retrieved data from the server in grid control.',
    Type: 'Story',
    Priority: 'High',
    Tags: 'Database,SQL',
    StoryPoints: 5.5,
    Assignee: 'Margaret hamilt',
    /* 'RankId': 4, */
    // Color: '#008000',
    // ClassName: 'e-story, e-high, e-margaret-hamilt',
  },
  {
    Id: 'Task 11',
    Project: 'Project 2',
    Title: 'Task - 29016',
    Status: 'InProgress',
    Summary: 'Fix cannot open user’s default database SQL error.',
    Priority: 'Critical',
    Type: 'Bug',
    Tags: 'Database,Sql2008',
    StoryPoints: 2.5,
    Assignee: 'Janet Leverling',
    /* 'RankId': 4, */
    // Color: '#ff0000',
    // ClassName: 'e-bug, e-critical, e-janet-leverling',
  },
  {
    Id: 'Task 12',
    Project: 'Project 1',
    Title: 'Task - 29017',
    Status: 'Review',
    Summary: 'Fix the issues reported in data binding.',
    Type: 'Story',
    Priority: 'Normal',
    Tags: 'DataBinding',
    StoryPoints: '3.5',
    Assignee: 'Janet Leverling',
    /* 'RankId': 4, */
    // Color: '#008000',
    // ClassName: 'e-story, e-normal, e-janet-leverling',
  },
  {
    Id: 'Task 13',
    Project: 'Project 1',
    Title: 'Task - 29018',
    Status: 'Close',
    Summary: 'Analyze SQL server 2008 connection.',
    Type: 'Epic',
    Priority: 'Release Breaker',
    Tags: 'Grid,Sql',
    StoryPoints: 2,
    Assignee: 'Andrew Fuller',
    /* 'RankId': 4, */
    // Color: '#008000',
    // ClassName: 'e-epic, e-release, e-andrew-fuller',
  },
  {
    Id: 'Task 14',
    Project: 'Project 2',
    Title: 'Task - 29019',
    Status: 'InProgress',
    Summary: 'Validate dataBinding issues.',
    Type: 'Story',
    Priority: 'Low',
    Tags: 'Validation',
    StoryPoints: 1.5,
    Assignee: 'Margaret hamilt',
    /* 'RankId': 1, */
    // Color: '#008000',
    // ClassName: 'e-story, e-low, e-margaret-hamilt',
  },
  {
    Id: 'Task 15',
    Project: 'Project 3',
    Title: 'Task - 29020',
    Status: 'Close',
    Summary: 'Analyze grid control.',
    Type: 'Improvement',
    Priority: 'High',
    Tags: 'Analyze',
    StoryPoints: 2.5,
    Assignee: 'Margaret hamilt',
    /* 'RankId': 5, */
    // Color: '#008000',
    // ClassName: 'e-improvement, e-high, e-margaret-hamilt',
  },
  {
    Id: 'Task 16',
    Project: 'Project 4',
    Title: 'Task - 29021',
    Status: 'Close',
    Summary: 'Stored procedure for initial data binding of the grid.',
    Type: 'Others',
    Priority: 'Release Breaker',
    Tags: 'DataBinding',
    StoryPoints: 1.5,
    Assignee: 'Steven walker',
    /* 'RankId': 6, */
    // Color: '#5187c6',
    // ClassName: 'e-others, e-release, e-steven-walker',
  },
  {
    Id: 'Task 17',
    Project: 'Project 5',
    Title: 'Task - 29022',
    Status: 'Close',
    Summary: 'Analyze stored procedures.',
    Type: 'Story',
    Priority: 'Release Breaker',
    Tags: 'Procedures',
    StoryPoints: 5.5,
    Assignee: 'Janet Leverling',
    /* 'RankId': 7, */
    // Color: '#008000',
    // ClassName: 'e-story, e-release, e-janet-leverling',
  },
  {
    Id: 'Task 18',
    Project: 'Project 6',
    Title: 'Task - 29023',
    Status: 'Validate',
    Summary: 'Validate editing issues.',
    Type: 'Story',
    Priority: 'Critical',
    Tags: 'Editing',
    StoryPoints: 1,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 1, */
    // Color: '#008000',
    // ClassName: 'e-story, e-critical, e-nancy-davloio',
  },
  {
    Id: 'Task 19',
    Project: 'Project 6',
    Title: 'Task - 29024',
    Status: 'Review',
    Summary: 'Test editing functionality.',
    Type: 'Story',
    Priority: 'Normal',
    Tags: 'Editing,Test',
    StoryPoints: 0.5,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 5, */
    // Color: '#008000',
    // ClassName: 'e-story, e-normal, e-nancy-davloio',
  },
  {
    Id: 'Task 20',
    Project: 'Project 5',
    Title: 'Task - 29025',
    Status: 'Open',
    Summary: 'Enhance editing functionality.',
    Type: 'Improvement',
    Priority: 'Low',
    Tags: 'Editing',
    StoryPoints: 3.5,
    Assignee: 'Andrew Fuller',
    /* 'RankId': 5, */
    // Color: '#57b94c',
    // ClassName: 'e-improvement, e-low, e-andrew-fuller',
  },
  {
    Id: 'Task 21',
    Project: 'Project 4',
    Title: 'Task - 29026',
    Status: 'InProgress',
    Summary: 'Improve the performance of the editing functionality.',
    Type: 'Epic',
    Priority: 'High',
    Tags: 'Performance',
    StoryPoints: 6,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 5, */
    // Color: '#edba3c',
    // ClassName: 'e-epic, e-high, e-nancy-davloio',
  },
  {
    Id: 'Task 22',
    Project: 'Project 3',
    Title: 'Task - 29027',
    Status: 'Open',
    Summary: 'Arrange web meeting with the customer to show editing demo.',
    Type: 'Others',
    Priority: 'High',
    Tags: 'Meeting,Editing',
    StoryPoints: 5.5,
    Assignee: 'Steven walker',
    /* 'RankId': 6, */
    // Color: '#5187c6',
    // ClassName: 'e-others, e-high, e-steven-walker',
  },
  {
    Id: 'Task 23',
    Project: 'Project 2',
    Title: 'Task - 29029',
    Status: 'Review',
    Summary: 'Fix the editing issues reported by the customer.',
    Type: 'Others',
    Priority: 'Low',
    Tags: 'Editing,Fix',
    StoryPoints: '3.5',
    Assignee: 'Janet Leverling',
    /* 'RankId': 6, */
    // Color: '#ff0000',
    // ClassName: 'e-others, e-low, e-janet-leverling',
  },
  {
    Id: 'Task 24',
    Project: 'Project 1',
    Title: 'Task - 29030',
    Status: 'Open',
    Summary: 'Fix the issues reported by the customer.',
    Type: 'Bug',
    Priority: 'Critical',
    Tags: 'Customer',
    StoryPoints: '3.5',
    Assignee: 'Steven walker',
    /* 'RankId': 1, */
    // Color: '#ff0000',
    // ClassName: 'e-bug, e-critical, e-steven-walker',
  },
  {
    Id: 'Task 25',
    Project: 'Project 1',
    Title: 'Task - 29031',
    Status: 'Close',
    Summary: 'Fix the issues reported in Safari browser.',
    Type: 'Bug',
    Priority: 'Release Breaker',
    Tags: 'Fix,Safari',
    StoryPoints: 1.5,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 2, */
    // Color: '#ff0000',
    // ClassName: 'e-bug, e-release, e-nancy-davloio',
  },
  {
    Id: 'Task 26',
    Project: 'Project 2',
    Title: 'Task - 29032',
    Status: 'Testing',
    Summary: 'Check Login page validation.',
    Type: 'Story',
    Priority: 'Release Breaker',
    Tags: 'Testing',
    StoryPoints: 0.5,
    Assignee: 'Michael Suyama',
    /* 'RankId': 3, */
    // Color: '#008000',
    // ClassName: 'e-story, e-release, e-michael-suyama',
  },
  {
    Id: 'Task 27',
    Project: 'Project 3',
    Title: 'Task - 29033',
    Status: 'Testing',
    Summary: 'Fix the issues reported in data binding.',
    Type: 'Story',
    Priority: 'Normal',
    Tags: 'DataBinding',
    StoryPoints: '3.5',
    Assignee: 'Janet Leverling',
    /* 'RankId': 4, */
    // Color: '#008000',
    // ClassName: 'e-story, e-normal, e-janet-leverling',
  },
  {
    Id: 'Task 28',
    Project: 'Project 4',
    Title: 'Task - 29034',
    Status: 'Testing',
    Summary: 'Test editing functionality.',
    Type: 'Story',
    Priority: 'Normal',
    Tags: 'Editing,Test',
    StoryPoints: 0.5,
    Assignee: 'Nancy Davloio',
    /* 'RankId': 5, */
    // Color: '#008000',
    // ClassName: 'e-story, e-normal, e-nancy-davloio',
  },
  {
    Id: 'Task 29',
    Project: 'Project 5',
    Title: 'Task - 29035',
    Status: 'Open',
    Summary: 'Fix editing issues reported in Firefox.',
    Type: 'Epic',
    Priority: 'Critical',
    Tags: 'Editing,Fix',
    StoryPoints: 1.5,
    Assignee: 'Robert King',
    /* 'RankId': 7, */
    // Color: '#ff0000',
    // ClassName: 'e-epic, e-critical, e-robert-king',
  },
  {
    Id: 'Task 30',
    Project: 'Project 6',
    Title: 'Task - 29036',
    Status: 'Testing',
    Summary: 'Test editing feature in the IE browser.',
    Type: 'Story',
    Priority: 'Normal',
    Tags: 'Testing',
    StoryPoints: 5.5,
    Assignee: 'Janet Leverling',
    /* 'RankId': 10, */
    // Color: '#008000',
    // ClassName: 'e-story, e-normal, e-janet-leverling',
  },
];

// export let cardData: Object[] = [
//   {
//     'Id': 'Task 1',
//     'Project': 'Project 1',
//     'Title': 'Task - 29001',
//     'Status': 'Open',
//     'Summary': 'Analyze customer requirements.',
//     'Priority': 'High',
//     'Tags': 'Bug, Release Bug',
//     /* 'RankId': 1, */
//     'Assignee': 'Nancy Davloio'
//   },
//   {
//     'Id': 'Task 2',
//     'Project': 'Project 2',
//     'Title': 'Task - 29002',
//     'Status': 'InProgress',
//     'Summary': 'Add responsive support to applicaton',
//     'Priority': 'Low',
//     'Tags': 'Story, Kanban',
//     /* 'RankId': 1, */
//     'Assignee': 'Andrew Fuller'
//   },
//   {
//     'Id': 'Task 3',
//     'Project': 'Project 3',
//     'Title': 'Task - 29003',
//     'Status': 'Open',
//     'Summary': 'Show the retrived data from the server in grid control.',
//     'Priority': 'High',
//     'Tags': 'Bug, Breaking Issue',
//     /* 'RankId': 2, */
//     'Assignee': 'Janet Leverling'
//   },
//   {
//     'Id': 'Task 4',
//     'Project': 'Project 4',
//     'Title': 'Task - 29004',
//     'Status': 'Open',
//     'Summary': 'Fix the issues reported in the IE browser.',
//     'Priority': 'High',
//     'Tags': 'Bug, Customer',
//     /* 'RankId': 3, */
//     'Assignee': 'Andrew Fuller'
//   },
//   {
//     'Id': 'Task 5',
//     'Project': 'Project 5',
//     'Title': 'Task - 29005',
//     'Status': 'Review',
//     'Summary': 'Improve application performance.',
//     'Priority': 'Normal',
//     'Tags': 'Story, Kanban',
//     /* 'RankId': 1, */
//     'Assignee': 'Steven walker'
//   },
//   {
//     'Id': 'Task 6',
//     'Project': 'Project 6',
//     'Title': 'Task - 29009',
//     'Status': 'Review',
//     'Summary': 'API Improvements.',
//     'Priority': 'Critical',
//     'Tags': 'Bug, Customer',
//     /* 'RankId': 2, */
//     'Assignee': 'Nancy Davloio'
//   },
//   {
//     'Id': 'Task 7',
//     'Project': 'Project 6',
//     'Title': 'Task - 29010',
//     'Status': 'Close',
//     'Summary': 'Fix cannot open user\'s default database sql error.',
//     'Priority': 'High',
//     'Tags': 'Bug, Internal',
//     /* 'RankId': 8, */
//     'Assignee': 'Margaret hamilt'
//   },
//   {
//     'Id': 'Task 8',
//     'Project': 'Project 5',
//     'Title': 'Task - 29015',
//     'Status': 'Open',
//     'Summary': 'Fix the filtering issues reported in safari.',
//     'Priority': 'Critical',
//     'Tags': 'Bug, Breaking Issue',
//     /* 'RankId': 4, */
//     'Assignee': 'Margaret hamilt'
//   },
//   {
//     'Id': 'Task 9',
//     'Project': 'Project 4',
//     'Title': 'Task - 29016',
//     'Status': 'Review',
//     'Summary': 'Fix the issues reported in IE browser.',
//     'Priority': 'High',
//     'Tags': 'Bug, Customer',
//     /* 'RankId': 3, */
//     'Assignee': 'Andrew Fuller'
//   },
//   {
//     'Id': 'Task 10',
//     'Project': 'Project 3',
//     'Title': 'Task - 29017',
//     'Status': 'Review',
//     'Summary': 'Enhance editing functionality.',
//     'Priority': 'Normal',
//     'Tags': 'Story, Kanban',
//     /* 'RankId': 4, */
//     'Assignee': 'Janet Leverling'
//   },
//   {
//     'Id': 'Task 11',
//     'Project': 'Project 2',
//     'Title': 'Task - 29018',
//     'Status': 'Close',
//     'Summary': 'Arrange web meeting with customer to get login page requirement.',
//     'Priority': 'High',
//     'Tags': 'Feature',
//     /* 'RankId': 1, */
//     'Assignee': 'Andrew Fuller'
//   },
//   {
//     'Id': 'Task 12',
//     'Project': 'Project 1',
//     'Title': 'Task - 29020',
//     'Status': 'Close',
//     'Summary': 'Login page validation.',
//     'Priority': 'Low',
//     'Tags': 'Bug',
//     /* 'RankId': 2, */
//     'Assignee': 'Margaret hamilt'
//   },
//   {
//     'Id': 'Task 13',
//     'Project': 'Project 1',
//     'Title': 'Task - 29021',
//     'Status': 'Close',
//     'Summary': 'Test the application in IE browser.',
//     'Priority': 'Normal',
//     'Tags': 'Bug',
//     /* 'RankId': 3, */
//     'Assignee': 'Steven walker'
//   },
//   {
//     'Id': 'Task 14',
//     'Project': 'Project 2',
//     'Title': 'Task - 29022',
//     'Status': 'Close',
//     'Summary': 'Analyze stored procedure.',
//     'Priority': 'Critical',
//     'Tags': 'CustomSample',
//     /* 'RankId': 4, */
//     'Assignee': 'Janet Leverling'
//   },
//   {
//     'Id': 'Task 15',
//     'Project': 'Project 3',
//     'Title': 'Task - 29024',
//     'Status': 'Review',
//     'Summary': 'Check login page validation.',
//     'Priority': 'Low',
//     'Tags': 'Story',
//     /* 'RankId': 5, */
//     'Assignee': 'Nancy Davloio'
//   },
//   {
//     'Id': 'Task 16',
//     'Project': 'Project 4',
//     'Title': 'Task - 29025',
//     'Status': 'Close',
//     'Summary': 'Add input validation for editing.',
//     'Priority': 'Critical',
//     'Tags': 'Bug, Breaking Issue',
//     /* 'RankId': 5, */
//     'Assignee': 'Andrew Fuller'
//   },
//   {
//     'Id': 'Task 17',
//     'Project': 'Project 5',
//     'Title': 'Task - 29026',
//     'Status': 'InProgress',
//     'Summary': 'Improve performance of editing functionality.',
//     'Priority': 'Critical',
//     'Tags': 'Bug, Customer',
//     /* 'RankId': 2, */
//     'Assignee': 'Nancy Davloio'
//   },
//   {
//     'Id': 'Task 18',
//     'Project': 'Project 6',
//     'Title': 'Task - 29027',
//     'Status': 'Open',
//     'Summary': 'Arrange web meeting for cutomer requirement.',
//     'Priority': 'High',
//     'Tags': 'Story',
//     /* 'RankId': 5, */
//     'Assignee': 'Steven walker'
//   },
//   {
//     'Id': 'Task 19',
//     'Project': 'Project 6',
//     'Title': 'Task - 29029',
//     'Status': 'Review',
//     'Summary': 'Fix the issues reported by the customer.',
//     'Priority': 'High',
//     'Tags': 'Bug',
//     /* 'RankId': 6, */
//     'Assignee': 'Janet Leverling'
//   },
//   {
//     'Id': 'Task 20',
//     'Project': 'Project 5',
//     'Title': 'Task - 29030',
//     'Status': 'InProgress',
//     'Summary': 'Test editing functionality',
//     'Priority': 'Low',
//     'Tags': 'Story',
//     /* 'RankId': 3, */
//     'Assignee': 'Janet Leverling'
//   },
//   {
//     'Id': 'Task 21',
//     'Project': 'Project 4',
//     'Title': 'Task - 29031',
//     'Status': 'InProgress',
//     'Summary': 'Check filtering validation',
//     'Priority': 'Normal',
//     'Tags': 'Feature, Release',
//     /* 'RankId': 4, */
//     'Assignee': 'Janet Leverling'
//   },
//   {
//     'Id': 'Task 22',
//     'Project': 'Project 3',
//     'Title': 'Task - 29032',
//     'Status': 'InProgress',
//     'Summary': 'Arrange web meeting with customer to get login page requirement',
//     'Priority': 'Critical',
//     'Tags': 'Feature',
//     /* 'RankId': 5, */
//     'Assignee': 'Margaret hamilt'
//   },
//   {
//     'Id': 'Task 23',
//     'Project': 'Project 2',
//     'Title': 'Task - 29033',
//     'Status': 'Open',
//     'Summary': 'Arrange web meeting with customer to get editing requirements',
//     'Priority': 'Critical',
//     'Tags': 'Story, Improvement',
//     /* 'RankId': 6, */
//     'Assignee': 'Andrew Fuller'
//   },
//   {
//     'Id': 'Task 24',
//     'Project': 'Project 1',
//     'Title': 'Task - 29034',
//     'Status': 'InProgress',
//     'Summary': 'Fix the issues reported by the customer.',
//     'Priority': 'Critical',
//     'Tags': 'Bug, Customer',
//     /* 'RankId': 6, */
//     'Assignee': 'Steven walker'
//   },
//   {
//     'Id': 'Task 25',
//     'Project': 'Project 1',
//     'Title': 'Task - 29035',
//     'Status': 'Close',
//     'Summary': 'Fix the issues reported in Safari browser.',
//     'Priority': 'High',
//     'Tags': 'Bug',
//     /* 'RankId': 6, */
//     'Assignee': 'Nancy Davloio'
//   },
//   {
//     'Id': 'Task 26',
//     'Project': 'Project 2',
//     'Title': 'Task - 29036',
//     'Status': 'Review',
//     'Summary': 'Check Login page validation.',
//     'Priority': 'Critical',
//     'Tags': 'Bug, Customer',
//     /* 'RankId': 7, */
//     'Assignee': 'Margaret hamilt'
//   },
//   {
//     'Id': 'Task 27',
//     'Project': 'Project 3',
//     'Title': 'Task - 29037',
//     'Status': 'Open',
//     'Summary': 'Fix the issues reported in data binding.',
//     'Priority': 'Normal',
//     'Tags': 'Bug',
//     'StoryPoints': '3.5',
//     /* 'RankId': 7, */
//     'Assignee': 'Steven walker'
//   },
//   {
//     'Id': 'Task 28',
//     'Project': 'Project 4',
//     'Title': 'Task - 29038',
//     'Status': 'Close',
//     'Summary': 'Test editing functionality.',
//     'Priority': 'Normal',
//     'Tags': 'Story',
//     'StoryPoints': 0.5,
//     /* 'RankId': 7, */
//     'Assignee': 'Steven walker'
//   }
// ];
